name: Test Deploy by commit
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
