name: Test Deploy by commit
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  output-info:
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"
